# Generated by Django 2.0 on 2018-08-27 10:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('likes', '0003_auto_20180823_2111'),
    ]

    operations = [
    ]
