# Generated by Django 2.0 on 2018-06-16 17:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='blogtype',
            table='blog_type',
        ),
    ]
