# Generated by Django 2.0 on 2018-08-27 10:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_profile'),
        ('user', '0002_auto_20180823_1008'),
    ]

    operations = [
    ]
