# Generated by Django 2.0 on 2018-08-27 10:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_merge_20180827_1038'),
    ]

    operations = [
    ]
